version: '3.7'
services:
  pg:
    env_file:
      - .env
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=wildstyle
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.api
    expose:
      - '3000'
    environment:
      - DB_HOST=pg
    volumes:
      - .:/myapp
    depends_on:
      - pg
  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.web
    command: npm run dev
    expose:
      - '5000'
    environment:
      - API_BASE_URL=http://api:3000
    volumes:
      - .:/myapp
    depends_on:
      - api
  app:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 2000:2000
    depends_on:
      - web
      - api
  test_api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.api
    command: bundle exec rails server -b 0.0.0.0 --pid ./tmp/pids/test.pid
    expose:
      - '3000'
    environment:
      - DB_HOST=pg
      - RAILS_ENV=test
    volumes:
      - .:/myapp
    depends_on:
      - pg
  test_web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.web
    command: npm run dev
    expose:
      - '5000'
    environment:
      - API_BASE_URL=http://test_api:3000
    volumes:
      - .:/myapp
    depends_on:
      - test_api
  test:
    image: nginx
    volumes:
      - ./nginx.test.conf:/etc/nginx/nginx.conf
    ports:
      - 2001:2001
    depends_on:
      - test_web
      - test_api

volumes:
  pg_data:
