version: '3.7'
services:
  pg:
    env_file:
      - .env
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 3000:3000
    environment:
      - DB_HOST=pg
    volumes:
      - .:/myapp
    depends_on:
      - pg
  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - 5000:5000
    environment:
      - API_BASE_URL=http://api:3000
    volumes:
      - .:/myapp
    depends_on:
      - api
  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 2000:2000
    depends_on:
      - web
      - api
volumes:
  pg_data:
